# Setup
title: Yulan
description: 疯狂花生酱
url: https://yulan932.github.io
avatar: /zhimahu.png
paginate: 5
permalink: pretty
cover_image: /nuowei.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: yulan
  card: summary
logo: logo.png
social:
  name: yulan
  links:
    - https://twitter.com
    - https://github.com/yulan932
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: yulan
  url: https://github.com/yulan932
  email: 18970348275@163.com
